AllCops:
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"

Documentation:
    Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - "spec/**/*_spec.rb"

Style/SpaceBeforeFirstArg:
  Exclude:
    - "config/routes.rb"

Metrics/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https
