language: ruby
rvm:
  - 2.3.0
env:
  - RAILS_ENV=test
before_install:
 - sudo apt-get update
 - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
 - sudo apt-get install postgresql-client-common postgresql-9.4
 - sudo service postgresql start
before_script:
  - cp config/database.yml.example config/database.yml
script:
  - bin/rake db:create
  - bin/rake db:migrate
  - bin/rake
