version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          BUNDLE_PATH: vendor/bundle
          PG_HOST: localhost
          PG_USER: postgres
          PG_PORT: 5432
          PG_DB: healer_core_test
          RAILS_ENV: test
          RACK_ENV: test

      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - run: cp config/database.yml{.example,}
      - run: bundle install
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bin/rails db:create db:migrate --trace
      - run: bin/rake
